version: "3.8"

services:
  frontend:
    build:
      context: ./Client/react-vite-project
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ClanControlPanel;Username=postgres;Password=123

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ClanControlPanel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
