// <auto-generated />
using System;
using ClanControlPanel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClanControlPanel.Infrastructure.Migrations
{
    [DbContext(typeof(ClanControlPanelContext))]
    [Migration("20250507212222_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.ClanMoneyDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ChangeAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("CustomReason")
                        .HasColumnType("text");

                    b.Property<int>("ReasonDb")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmountAfterAction")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("ClanMoney");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.ClanWarAttendanceDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsenceReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasPresent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("ClanWarAttendance");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.EquipmentDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemDbId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.GoldenDropAttendanceDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("GoldenDropAttendance");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.ItemDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.PlayerDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.ScheduleDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDbId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.UserDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.ClanWarAttendanceDb", b =>
                {
                    b.HasOne("ClanControlPanel.Infrastructure.Data.PlayerDb", "PlayerDb")
                        .WithMany("ClanWarAttendances")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerDb");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.EquipmentDb", b =>
                {
                    b.HasOne("ClanControlPanel.Infrastructure.Data.ItemDb", "ItemDb")
                        .WithMany()
                        .HasForeignKey("ItemDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClanControlPanel.Infrastructure.Data.PlayerDb", "PlayerDb")
                        .WithMany("Equipments")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemDb");

                    b.Navigation("PlayerDb");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.GoldenDropAttendanceDb", b =>
                {
                    b.HasOne("ClanControlPanel.Infrastructure.Data.PlayerDb", "PlayerDb")
                        .WithMany("GoldenDropAttendances")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerDb");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.PlayerDb", b =>
                {
                    b.HasOne("ClanControlPanel.Infrastructure.Data.UserDb", "UserDb")
                        .WithOne("Player")
                        .HasForeignKey("ClanControlPanel.Infrastructure.Data.PlayerDb", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDb");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.ScheduleDb", b =>
                {
                    b.HasOne("ClanControlPanel.Infrastructure.Data.PlayerDb", "PlayerDb")
                        .WithMany("Schedules")
                        .HasForeignKey("PlayerDbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerDb");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.PlayerDb", b =>
                {
                    b.Navigation("ClanWarAttendances");

                    b.Navigation("Equipments");

                    b.Navigation("GoldenDropAttendances");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ClanControlPanel.Infrastructure.Data.UserDb", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
